[project]
name = "demo-transformer"
version = "0.1.0"
description = ""
authors = [
    {name = "Zhurun Zhang",email = "zhurunz@amazon.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch (>=2.7.0,<3.0.0)",
    "numpy (>=2.2.6,<3.0.0)"
]

[tool.poetry]
packages = [{include = "demo_transformer", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
